import Head from 'next/head'
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { TokenContextProvider } from './components_waiter/tokenContext';
import './styles/globals.css'

export default function App({ Component, pageProps }) {
  
  const router = useRouter()
   useEffect(() => {

   const isNotAuthenticated = localStorage.getItem('userId') === '';
  
   if (isNotAuthenticated && router.pathname !== '/') {
    router.push('/');
  }
  }, [])

  return (
    <>
    <Head>
    <title>Burger Queen</title>
      <meta name="login/home" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/burgericon.png" />
      <meta charSet="utf-8" />
    </Head>
    <TokenContextProvider>
      <Component {...pageProps} />
    </TokenContextProvider>
    
    </>
  )
}
