import Head from 'next/head'
import LoginForm from './components_login/loginform'
import styles from './styles/Login.module.css'

export default function Home() {
  return (
    <>
    <Head>
      <title>Burger Queen</title>
      <meta name="login/home" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/burgericon.png" />
    </Head>
    <header style={{display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
      <img src='/bqlogo.png' className={styles.logoBq} />
      <h2 className={styles.logintitle} >Burger Queen</h2>
    </header>
      <main className={styles.login_container} >
        <LoginForm/>
        <img src='/burger_login.png' className={styles.loginburger} />
      </main>
      
    </>
  )
}
